CREATE TABLE IF NOT EXISTS `user` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(50) CHARACTER SET utf16 NOT NULL,
  `PASSWORD` varchar(1024) CHARACTER SET utf16 NOT NULL,
  `NAME` varchar(1024) CHARACTER SET utf16 NOT NULL,
  `EMAIL` varchar(1024) NOT NULL,
  `PHONE_NUMBER` varchar(15) CHARACTER SET utf16 NOT NULL,
  `TYPE` smallint(6) NOT NULL,
  `UPDATED_PASSWORD_DATE` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `UPDATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1000002 DEFAULT CHARSET=latin1;

